spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${GATEWAY_PORT:8080}

info:
  app:
    name: Gateway service
    description: This service is the entrypoint for the other services
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.uuid}}
