---
name: "master-prerelease"

on:
  push:
    branches:
      - "master"

jobs:
  tagged-release:
    name: "Mater Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Prepare version 'latest'
        run: mvn versions:set -DnewVersion=latest

      - name: Prepare version 'latest' for gateway-service
        run: mvn versions:set -DnewVersion=latest -f gateway-service/pom.xml

      - name: Package with Maven
        run: mvn -B -U package
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            */target/*.jar
